development:
  adapter: postgresql
  encoding: unicode
  database: databasename
  pool: 5
  username: will
  password: secret

test:
  adapter: postgresql
  encoding: unicode
  database: testdatabasename
  pool: 5
  username: will
  password: secret

production:
  adapter: postgresql
  encoding: unicode
  database: productiondatabasename
  pool: 5
  username: will
  password: secret
