# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee3e5bcff600b797429294339a4a6e1d780fcf688cac3d0628e2fc1606f952ec264e4cd5e475d717391542b2db5a4b50c60ae44f40b86dec11a8e2537615c8c5

test:
  secret_key_base: 40308ae262cc08f1b276f0c5abb205f55c2b32c5285c93ac35830430294249214fd78aa65e19e2d60764ec8fad0ff705a672d9017e603f8d745a0236a9cb19a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
